version: '3.3'

services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    env_file: ./.env
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  webservice:
    build: .
    container_name: web-service
    env_file: ./.env
    restart: always
    depends_on:
      - mysql
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: yarn start

volumes:
  db_data: {}
